### ISSUE TITLE
'openStartGlob' opens files from node_modules directory

### ISSUE THREAD

**Issue by nick-rudenko** [masliu/vscode-exercism#17]
I am excited to discover Exercism and I did that by simply finding your nice extension on the Marketplace :)

I am working on the JavaScript track and for every exercise I have to download needed dependencies by running `npm install` which creates a `node_modules` directory. If I click on "Open and start" for a task with already downloaded modules, it also opens countless amount of files from the `node_modules` directory.

![Screenshot from 2019-08-06 22-26-59](https://user-images.githubusercontent.com/36961943/62571164-61b0e200-b899-11e9-9d52-cbe225060b70.png)

I tried to change the `openStartGlob` to exclude it, but it doesn't help:
```
"**/!(node_modules)/!(README).{fs,js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,hpp,java,lua,rb,sh,vb,php,py}"
```

Thanks!

**Comment by masliu** [comment]
I apologize for having you deal with that nasty bug and my late response. The following should work:

```json
  "exercism.openStartGlob": "{,!(node_modules)/**/}!(README.md).{js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,java,lua,rb,sh,vb,php,py}",
```

I'm also going to limit the number of files that the extension can open.

**Comment by nick-rudenko** [comment]
Your solution works great, thanks!

I also added an exclusion for config files:

````
"exercism.openStartGlob": "{,!(node_modules)/**/}!(README|*.config).{js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,java,lua,rb,sh,vb,php,py}"
````
