### ISSUE TITLE
Trying to download locked exercises displays no error

### ISSUE THREAD

**Issue by masliu** [masliu/vscode-exercism#18]
Unfortunately, I am having problems again in regards with the Fsharp track. I realize it is not necessarily your domain but I thought I'd let you know...I am unable to download files! Both the webview and the context menu produce the same result of showing a progress bar but then no files actually appear within my file system and no error is thrown. 

Thanks
Evan

_Originally posted by @evanricard in https://github.com/masliu/vscode-exercism/issues/16#issuecomment-515716591_

**Comment by masliu** [comment]
@evanricard Does this happen with any other tracks?

**Comment by masliu** [comment]
Okay, I believe this is a problem with the exercism-cli. Can you try manually downloading the exercise that isn't downloading and tell me if it works?

**Comment by masliu** [comment]
It used to be that trying to download an exercise you hadn't yet unlocked would raise an error, but exercism-cli no longer seems to have that feature. I can resolve this issue by checking to see if the exercise directory was actually downloaded, but ideally this should be fixed by exercism-cli.

**Comment by nick-rudenko** [comment]
I just enrolled the Python track, downloaded the very first Hello World task and a random not yet unlocked, both exercises appear in the Downloaded Exercises but no folders or files were downloaded for the second one without any errors.
Then tried to do the same for a locked task via exercism-cli. It shows that the exercise was downloaded, but it wasn't in fact.

**Comment by masliu** [comment]
I have reported the issue upstream but will keep this open until it's resolved.
