### ISSUE TITLE
Open & Start button does not work

### ISSUE THREAD

**Issue by bilboquet** [masliu/vscode-exercism#20]
Hello,

Thank a lot for this very useful VSCode extension.
I really love it, but I have a little problem, as said in the tittle, the Open & Start button does not work. When I click on it, nothing happen.

Please note that, even if the download works well, at the end of the download I get a notfication message "Cannot read property 'workspace' of undefined". I don't know if it's related or not.

I hope you can help me,

Regards

**Comment by masliu** [comment]
I'm glad you've found it useful!

Are you experiencing this issue with all tracks? What operating system are you using?

**Comment by Onizuka89** [comment]
Similar sounding issue. I checked the user.json file, and workspace exist for me.
Using windows, and not sure how to verify if the files are being downloaded properly.

**Comment by masliu** [comment]
@Onizuka89 Can you check the workspace directory and see if the files are being downloaded? Or if you expand the exercise node in the explorer can you see the file tree? Do the files you want to open actually exist?

We also rely on exercism-cli to report errors so that we can stop certain operations like download (see https://github.com/exercism/cli/issues/885). I don't know if that's related to this problem, but it seems like exercism is running into an error (maybe you haven't unlocked the exercise?) but not reporting it so the download function progresses believing the operation was successful.

**Comment by masliu** [comment]
You should also know that you have to enroll in a track via the website before being able to run any of its exercises.

**Comment by Onizuka89** [comment]
Get this when enrolled, there is 2 exercises already in the folder for that languages.
![image](https://user-images.githubusercontent.com/952150/67163725-b6c9a380-f372-11e9-9669-537587e10759.png)

**Comment by bilboquet** [comment]
Hello,

Sorry, I missed the notification of your reply :/
I have the "workspace" key and it is correctly defined to a folder.
The download works like a charm.
I only have problem with the open button.
I work on Ubuntu 19.10.
The problem happens with tracks I'm enrolled with and with exercises that I have unlocked.

Thanks for your help

**Comment by bilboquet** [comment]
Can I provide some information to help you fix this issue?

**Comment by masliu** [comment]
Sorry I haven't been available recently. I don't really know how to reproduce this because everything seems to work on my system. Could someone please provide me the exact steps to reproduce?

**Comment by BobbyMcWho** [comment]
I was having this same issue with Elixir
Open Your VSCode Settings -> Extensions -> Exercism

Make sure the file extension of your language is in the list of options (default is `{,!(node_modules)/**/}!(README).{dart,fs,js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,hpp,java,lua,rb,sh,vb,php,py}` as of v1.16.9 of this extension) 

I changed this to 
`{,!(node_modules)/**/}{,!(README).{dart,fs,js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,hpp,java,lua,rb,sh,vb,php,py,ex}}{,*_test.exs}` and now when I open & start an elixir exercise, it opens the elixir code file as well as the test file. The only thing that would improve this workflow is if it set the terminal's path to be the working dir of that project!

**Comment by masliu** [comment]
@BobbyMcWho You were getting the "Cannot read property 'workspace' of undefined" error?
