### ISSUE TITLE
All tracks show 0/... despite the web dashboard showing non zero

### ISSUE THREAD

**Issue by lestephane** [masliu/vscode-exercism#24]
Despite having done 1 exercise for one of my tracks
![image](https://user-images.githubusercontent.com/5460884/77992652-259e2600-732f-11ea-911f-f9543b8a31e8.png)

The extension shows 0
![image](https://user-images.githubusercontent.com/5460884/77992713-4a929900-732f-11ea-95ae-2ef808b9b802.png)

In fact all tracks show 0

When I click `complete` the count **does** goes up, but I'd like to understand why this information is not pulled directly from exercism.io.

**Comment by masliu** [comment]
The extension actually just wraps around exercism-cli and scrapes the list of tracks/extensions from the website so it doesn't actually have the ability to synchronize :disappointed:. See https://github.com/masliu/vscode-exercism#faq for the relevant issue to follow/upvote.
